Improve some role descriptions
EnhancedNetwork/TownofHost-Enhanced pull request #1231
Opened 2024-09-27 01:47 UTC by KingPanda360

2024-09-27 04:05 UTC, 0xDrMoe requested changes
Please amend the changes so approval can be given. Once amended, changes will be merged.

2024-09-27 04:05 UTC, 0xDrMoe commented on Resources/Lang/en_US.json
> +  "PestilenceInfoLong": "(Apocalypse):\nAs Pestilence, you're an unstoppable machine.\nAny attack towards you will be reflected towards them.\nIndirect kills don't even kill you.\n\nOnly way to kill
This indicates the non-Pestilence player may misguess to exile Pestilence. Either reword it or re-add "it"

2024-09-27 04:05 UTC, 0xDrMoe commented on Resources/Lang/en_US.json
> +  "FamineInfoLong": "(Apocalypse): \nOnce the Baker has the set amount of people with bread alive, they will become Famine. Suppose Famine is not voted out after the meeting. Then they become Famine,
This seems wrong to the tongue. Why are you saying "Suppose"? You can reword this significantly better.

2024-09-27 04:05 UTC, 0xDrMoe commented on Resources/Lang/en_US.json
> +  "EvaderInfoLong": "(Add-ons):\nWhen the Evader gets voted out, there is a chance the Evader will not get ejected. (Chance set by the Host.)",
Good, just remove the second "Evader in the sentence as it is redundant. Consider using "they".

2024-09-27 04:05 UTC, 0xDrMoe commented on Resources/Lang/en_US.json
> -
Please re-add this line. It is the divider between addon descriptions and settings below.

2024-09-28 07:37 UTC, Tommy-XL commented
@KingPanda360 can you fix?
I want sync translations

2024-09-28 14:52 UTC, KingPanda360 commented
> @KingPanda360 can you fix? I want sync translations

Fixed

2024-09-29 04:29 UTC, merged