exorcist
EnhancedNetwork/TownofHost-Enhanced pull request #1278
Opened 2024-11-03 20:03 UTC by laikrai

Adds a new Impostor role exorcist
Idea: https://discord.com/channels/1094344790910455908/1301246276804939828
Thanks to @MargaretTheFool for helping with some stuff

2024-11-03 20:27 UTC, MargaretTheFool requested changes

2024-11-03 20:27 UTC, MargaretTheFool commented on Resources/Lang/en_US.json
> +  "ExorcistInfoLong": "(Impostors):\nAs the Exorcist, you can use /ex in meeting to exorcise a player who won't shut up. The exorcised player will die. You'll lose your ability if you excersise too m
"ExorcistInfoLong": "(Impostors):\nAs the Exorcist, you can use /ex in meeting to kill a player who speaks in the next set amount of seconds after using the command. Depending on the settings, the Exorcist can kill multiple people in one meeting. You'll lose your ability if you excersise too many people.",

2024-11-03 20:27 UTC, MargaretTheFool commented on Resources/Lang/en_US.json
> +  "DeathReason.Excersized": "Excersized",
"DeathReason.Excersized": "Exorcised",

2024-11-03 20:27 UTC, MargaretTheFool commented on Resources/Lang/en_US.json
> +  "ExorcistKill": "<b>{0}</b> was Exorcismed",
"ExorcistKill": "<b>{0}</b> was Exorcised",

2024-11-03 20:27 UTC, MargaretTheFool commented on Resources/Lang/en_US.json
> +  "ExcorismLimitMeeting": "How many times can exorcism be used per meeting",
"ExcorismLimitMeeting": "Max exorcises per meeting",

2024-11-03 20:27 UTC, MargaretTheFool commented on Resources/Lang/en_US.json
> +  "ExcorismPerGame": "How many times can exorcism be used per game",
"ExcorismPerGame": "Max exorcises per game",

2024-11-03 20:27 UTC, MargaretTheFool commented on Resources/Lang/en_US.json
> +  "ExcorismActiveFor": "How long should exorcism last for",
"ExcorismActiveFor": "Exorcism Duration",

2024-11-03 20:27 UTC, MargaretTheFool commented on Resources/Lang/en_US.json
> +  "ExcorismDelay": "How long should the delay be",
"ExcorismDelay": "Exorcism Delay",

2024-11-03 20:27 UTC, MargaretTheFool commented on Roles/Impostor/Exorcist.cs
> +    private const int Id = 30200;
30800 so i dont have to offset all my coven ids
(I edited this in the liveshare I don't know why it didn't change)

2024-11-15 00:55 UTC, laikrai commented
I'll try to make the exorcist button next to send button

2024-11-18 00:14 UTC, laikrai commented
![image](https://github.com/user-attachments/assets/1654f842-023a-437b-aa92-2dee66fe112c)
here's how it looks like

2024-11-26 12:50 UTC, NikoCat233 commented
Conflicts occurs

2024-11-26 12:55 UTC, NikoCat233 commented
Seems like other roles commands can trigger death
can you add a option to exclude this?

BTW messages like /id and /dump still got posted even after canceled so you need to whitelist these

2024-11-26 12:57 UTC, NikoCat233 commented
Add a ondead check that disables Exorcism immediately during meeting if exorcist got killed

2024-11-26 13:01 UTC, NikoCat233 requested changes

2024-11-26 13:01 UTC, NikoCat233 commented on Roles/Impostor/Exorcist.cs
> +            if (PlayerControl.LocalPlayer.Is(CustomRoles.Exorcist) && PlayerControl.LocalPlayer.IsAlive())
always run on meeting no matter player is alive

2024-11-26 13:01 UTC, NikoCat233 commented on Roles/Impostor/Exorcist.cs
> +        PlayerControl pc = PlayerControl.LocalPlayer;
check swapper code
no matter player is alive or not
first destory the existing button

if player is alive, then spawn it

2024-11-26 23:04 UTC, laikrai commented on Roles/Impostor/Exorcist.cs
> +        Options.SetupRoleOptions(Id, TabGroup.ImpostorRoles, CustomRoles.Exorcist);
im using ExorcistPlayer to keep track of who activated the exorcism

2025-02-25 05:49 UTC, Tommy-XL commented
Pls sync witch dev_2.3.0

2025-05-09 19:45 UTC, MargaretTheFool commented
why does this have 993 commits, bro's farming fr

2025-05-09 19:58 UTC, merged