Fix Horse Mode crashing the game
EnhancedNetwork/TownofHost-Enhanced pull request #1302
Opened 2024-11-26 21:39 UTC by PEPPERcula

2024-11-29 10:43 UTC, NikoCat233 commented on Patches/ChatCommandPatch.cs
> +using Assets.CoreScripts;
Fix this

2024-11-29 13:19 UTC, NikoCat233 commented
![image](https://github.com/user-attachments/assets/e8f5de8a-e0b1-40b0-93df-21ea8e7d7bcd)

2024-12-01 15:06 UTC, NikoCat233 commented
I dont know why you cant fix your chatcommandpatch
So i have to manually redo it

2024-12-01 15:06 UTC, NikoCat233 commented
Do not include mulitple features in a single pr next time

2024-12-01 15:07 UTC, NikoCat233 commented
Seems like you denied maintainers from editing your pr
Enable it pls

2024-12-01 15:12 UTC, NikoCat233 commented
bro your fork cant litterly build

2024-12-01 15:12 UTC, NikoCat233 commented
![image](https://github.com/user-attachments/assets/1c8a4790-9676-44ed-aa11-76d4034e7756)

2024-12-01 15:15 UTC, PEPPERcula commented
Idk why this happened but from before i only edited these lines and thats it. I didn't expect the whole file to change.
![Screenshot 2024-12-01 081202](https://github.com/user-attachments/assets/4fc5dd66-2291-4f57-904a-6816cd531634)

2024-12-01 15:15 UTC, NikoCat233 requested changes
Remove your changes in ChatCommandPatch
It cant be reviewed and it cant build

2024-12-02 02:07 UTC, merged